function [w_final K] = estimateK_square_pixels(v1, v2, v3);
    syms a b c d
    w = [ a   0  b/2; ...
          0   a  c/2; ...
         b/2 c/2  d];
    r1 = v1' * w * v2;
    r1coeffs = [coeffs(r1,a); ...
                coeffs(r1,b); ...
                coeffs(r1,c); ...
                coeffs(r1,d)];
    r2 = v2' * w * v3;
    r2coeffs = [coeffs(r2,a); ...
                coeffs(r2,b); ...
                coeffs(r2,c); ...
                coeffs(r2,d)];
    r3 = v3' * w * v1;
    r3coeffs = [coeffs(r3,a); ...
                coeffs(r3,b); ...
                coeffs(r3,c); ...
                coeffs(r3,d)];
    A = [r1coeffs(:,2)'; ...
         r2coeffs(:,2)'; ...
         r3coeffs(:,2)'];
    [~, ~, v] = svd(A);
    w_abcd = v(:,4);
    w_final = double(subs(w, {a, b, c, d}, {w_abcd(1), w_abcd(2), w_abcd(3), w_abcd(4)}));
    % w_inv = inv(w_final);
    K = inv(chol(w_final));
    K = K ./ K(3,3);